// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmouv66OGw8tfaRABkWrnXpw1Pk4EQJiQ',
    appId: '1:122143735547:web:474cf71a33bf9012b17a5e',
    messagingSenderId: '122143735547',
    projectId: 'iot1-24d06',
    authDomain: 'iot1-24d06.firebaseapp.com',
    databaseURL: 'https://iot1-24d06-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-24d06.firebasestorage.app',
    measurementId: 'G-7HGT97SK3P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANndkaPmEnQXtsKoPhHwQh69GbW3Mh8pk',
    appId: '1:122143735547:android:8d152ba350978338b17a5e',
    messagingSenderId: '122143735547',
    projectId: 'iot1-24d06',
    databaseURL: 'https://iot1-24d06-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-24d06.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBmmSRpm7JgV0dxEryHZHyXSaeFtu-eRg',
    appId: '1:122143735547:ios:967d81597d8d761eb17a5e',
    messagingSenderId: '122143735547',
    projectId: 'iot1-24d06',
    databaseURL: 'https://iot1-24d06-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-24d06.firebasestorage.app',
    iosBundleId: 'com.example.iotThi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBmmSRpm7JgV0dxEryHZHyXSaeFtu-eRg',
    appId: '1:122143735547:ios:967d81597d8d761eb17a5e',
    messagingSenderId: '122143735547',
    projectId: 'iot1-24d06',
    databaseURL: 'https://iot1-24d06-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-24d06.firebasestorage.app',
    iosBundleId: 'com.example.iotThi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmouv66OGw8tfaRABkWrnXpw1Pk4EQJiQ',
    appId: '1:122143735547:web:924cc4d8498a68b6b17a5e',
    messagingSenderId: '122143735547',
    projectId: 'iot1-24d06',
    authDomain: 'iot1-24d06.firebaseapp.com',
    databaseURL: 'https://iot1-24d06-default-rtdb.firebaseio.com',
    storageBucket: 'iot1-24d06.firebasestorage.app',
    measurementId: 'G-988G6JKBDF',
  );
}
